export const GET_ALL_COUNTRIES = "GET ALL COUNTRIES";
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY_BY_NAME";
export const COUNTRY_DETAIL = "COUNTRY_DETAIL";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const POST_ACTIVITIES = "POST_ACTIVITIES";
export const UPDATE_DISPLAYEDCOUNTRIES = "UPDATE_DISPLAYEDCOUNTRIES";